@startuml
'https://plantuml.com/class-diagram

interface Aware

interface Servlet
interface ServletConfig

class GenericServlet implements Servlet,ServletConfig

class HttpServlet extends GenericServlet


interface EnvironmentAware extends Aware {
    Environment getEnvironment()
}

interface ApplicationContextAware extends Aware{
    void setApplicationContext(ApplicationContext applicationContext)
}


interface EnvironmentCapable {
    void setEnvironment(Environment environment)
}

abstract class HttpServletBean extends HttpServlet implements EnvironmentCapable, EnvironmentAware{
    + void init()
    # void initServletBean()
}

abstract class FrameworkServlet extends HttpServletBean implements ApplicationContextAware{
    - WebApplicationContext webApplicationContext;
    # void initServletBean()
    # WebApplicationContext initWebApplicationContext()
    # void initFrameworkServlet()
    # void onRefresh(ApplicationContext context)
}

class DispatcherServlet extends FrameworkServlet{

}



interface ApplicationContext

interface WebApplicationContext extends ApplicationContext{
    String ROOT_WEB_APPLICATION_CONTEXT_ATTRIBUTE
    ServletContext getServletContext()
}


@enduml